spring:
  profiles:
    active: prod
openroute:
  security:
    token:
      secret: ${openroute_token}
mercadopago:
  webhook:
    secret:
      token: ${MERCADO_PAGO_WEBHOOK_SECRET}
  access:
    token: ${MERCADO_PAGO_ACCESS_TOKEN}