spring:
  profiles:
    active: prod
  mail:
    username: ${mail_username}
    password: ${mail_password}
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        security: TRACE
